language: generic
# superuser required
sudo: required
services:
  # install copy of docker
  - docker

before_install:
  - docker build -t gkeown03/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gkeown03/docker-react npm run test -- --coverage
